webeats:
    restart: always
    build: ./webeats
    links:
        - postgres:db
    ports:
        - "8000:8000"
    command: /usr/src/app/start.sh
    volumes:
        - /var/www/static/:/static

postgres:
    restart: always
    image: postgres:latest
    volumes:
        - pgdata:/var/lib/postgresql/data
