# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_extend_wunderlist_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_extend',
            name='state',
            field=models.IntegerField(null=True),
        ),
    ]
