# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_user_extend_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_extend',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
