# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ammount',
            new_name='amount',
        ),
    ]
