# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20160918_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='recipie',
            field=models.CharField(default='N/A', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='dish_pictures/'),
        ),
    ]
