# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20160918_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='recipie',
            new_name='recipe',
        ),
    ]
